# schema yml file for the sources

version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:

        - name: sales
          identifier: raw_gz_sales
          description: sales of Greenweez, one row per product_id in each orders id
          tests:
            - unique:
                column_name: "(orders_id || '_' ||pdt_id)"
          columns:
            - name: date_date
              description: date of purchase
              tests:
                - not_null
                
            - name: orders_id
              description: id per order
              tests: 
                - not_null
              
            - name: pdt_id
              description: id of product
              tests:
                - not_null
                
            - name: revenue
              description: revenue of product in that order
            - name: quantity
              description: the amount of products in that order
          # Freshness testing
          loaded_at_field: "cast(date_date as timestamp)"
          freshness:
            warn_after: {count: 90, period: day}

        - name: product
          identifier: raw_gz_product
          description: products of Greenweez with purchase_price
          columns:
            - name: products_id
              description: primary key, id of unique product
              tests:
                - unique 
                - not_null 
            - name: purchSE_PRICE
              description: purchase price of that product
              tests: 
                - not_null 
        - name: ship
          identifier: raw_gz_ship
          description: orders of Greenweez with log, ship costs and shipping fee
          columns:
            - name: orders_id
              description: id of the orders, primary key
              tests:
                - unique
                - not_null
            - name: shipping_fee
              description: the shipping fee cost per order
              tests:
                - not_null
            - name: logCOST
              description: logistics cost per order
              tests:
                - not_null
            - name: ship_cost
              description: cost of shipping per order
              tests:
                - not_null
              
